Toggle menu
ChaabaneAnas/PortfolioSetup_Mobile-Version-Setup pull request #17
Opened 2022-06-22 08:32 UTC by ChaabaneAnas

add closebtn functionality
add transition

2022-06-22 13:42 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @ChaabaneAnas, and @MaiRizk👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] I would suggest group members, commit equally to pair-programming projects.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 13:42 UTC, thecodechaser commented on README.md
> +2. **Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students.**
- [ ] You changed your README file with this new README. It looks like it belongs to linters. Please make sure to change this README file with a professional one. I would suggest you copy the README file from your main branch and replace this file.

2022-06-22 13:42 UTC, thecodechaser commented on index.html
>              <li> <a href="#contact">contact</a></li>
- [ ] Please use capitalization for `About` and `Contact` menu options.

2022-06-22 13:42 UTC, thecodechaser commented on index.html
> +         <a class="closebtn" id="closebtn">&times;</a>
- [ ] Please reduce the weight of your close(X) button and make sure it matches the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468) design.

### Your design

![image](https://user-images.githubusercontent.com/83803414/175043568-8da801ad-cc1e-4a1f-a4c4-a5996d9536ca.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/175043633-f81fb8e1-25f2-4c2a-8a6c-2471efae9ebe.png)

2022-06-22 14:13 UTC, Kossi-stack approved these changes
## Status: Approved ✔️

**Hi @ChaabaneAnas,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-06-23 09:28 UTC, ChaabaneAnas commented
Toggle menu aded

2022-06-23 09:28 UTC, merged